services:
  - type: web
    name: chainelect
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_CONTRACT_ADDRESS
        sync: false
      - key: VITE_NETWORK_ID
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 