services:
  - type: web
    name: chainelect-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: INFURA_SEPOLIA_URL
        value: https://sepolia.infura.io/v3/c9ce36a11fef47d3b611df8773fa71b1
      - key: PRIVATE_KEY
        sync: false 